---
- name: CentOS 7
  hosts: default
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: Find temporary files
      find:
        file_type: any
        paths:
          - /tmp
          - /var/tmp
        patterns: '*'
      register: tmp_files

    - name: Remove temporary files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ tmp_files.files }}"

    - name: Remove SSH host keys
      block:
        - name: Find SSH host keys
          find:
            paths: /etc/ssh
            patterns: '*host*key*'
          register: host_keys

        - name: Remove SSH host keys
          file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ host_keys.files }}"

    - name: Truncate files
      command: "truncate -s 0 {{ item }}"
      loop:
        - /etc/machine-id
        - /var/log/audit/audit.log
        - /var/log/wtmp
        - /var/log/lastlog

    - name: Batch commands
      shell: |
        sed -i -e "s/^#\\?PasswordAuthentication.*/PasswordAuthentication no/g" /etc/ssh/sshd_config
        yum -y remove epel-release
        rm -rf /root/anaconda-ks.cfg
        rm -rf /root/original-ks.cfg
        yum clean all
        rm -rf /var/cache/yum
        rm -rf /var/tmp/yum-*

    - name: Fill free space with zeroes
      shell: dd if=/dev/zero of=/zeroed_file bs=1M oflag=direct || /bin/true

    - name: Remove zeroed file
      file:
        path: /zeroed_file
        state: absent

    - name: Sync disc
      command: sync

    - name: Delete root password
      shell: passwd -d root

    - name: Lock root password
      shell: passwd -l root

    - name: Clear shell history
      shell: history -c
      ignore_errors: yes

